/** code generated by Kinyoshi */
package net.minecraft.src;

import java.util.Random;

public class BlockPetrifiedWood extends Block
{
    private Icon PetrifiedWoodTopIcon;
    private Icon PetrifiedWoodBottomIcon;

    protected BlockPetrifiedWood(int par1)
    {
        super(par1, Material.wood);
    }
    
    /**
     * When this method is called, your block should register all the icons it needs with the given IconRegister. This
     * is the only chance you get to register icons.
     */
    public void registerIcons(IconRegister par1IconRegister)
    {
        this.blockIcon = par1IconRegister.registerIcon("BlockPetrifiedWood");
        this.PetrifiedWoodTopIcon = par1IconRegister.registerIcon("BlockPetrifiedWood2");
        this.PetrifiedWoodBottomIcon = par1IconRegister.registerIcon("BlockPetrifiedWood2");
    } 
    

    /**
     * From the specified side and block metadata retrieves the blocks texture. Args: side, metadata
     */
    public Icon getIcon(int par1, int par2)
    {
        return par1 == 1 ? this.PetrifiedWoodTopIcon : (par1 == 0 ? this.PetrifiedWoodBottomIcon : this.blockIcon);
    }
    
    /**
     * Checks to see if its valid to put this block at the specified coordinates. Args: world, x, y, z
     */
    public boolean canPlaceBlockAt(World par1World, int par2, int par3, int par4)
    {
        int var5 = par1World.getBlockId(par2, par3 - 1, par4);
        return var5 == this.blockID ? true : (var5 != Block.sand.blockID ? false : (par1World.getBlockMaterial(par2 - 1, par3 - 1, par4) == Material.sand ? true : (par1World.getBlockMaterial(par2 + 1, par3 - 1, par4) == Material.sand ? true : (par1World.getBlockMaterial(par2, par3 - 1, par4 - 1) == Material.sand ? true : par1World.getBlockMaterial(par2, par3 - 1, par4 + 1) == Material.sand))));
    }

    /**
     * Can this block stay at this position.  Similar to canPlaceBlockAt except gets checked often with plants.
     */
    public boolean canBlockStay(World par1World, int par2, int par3, int par4)
    {
        return this.canPlaceBlockAt(par1World, par2, par3, par4);
    }
    
public int quantityDropped(Random par1Random)
{
         return 1 + par1Random.nextInt(2);
}

public int idDropped(int par1, Random par2Random, int par3)
{
         return mod_DesertPetrifiedWood.ItemPetrifiedWood.itemID;
}

    /**
     * Is this block (a) opaque and (b) a full 1m cube?  This determines whether or not to render the shared face of two
     * adjacent blocks and also whether the player can attach torches, redstone wire, etc to this block.
     */
    public boolean isOpaqueCube()
    {
        return false;
    }

    /**
     * If this block doesn't render as an ordinary block it will return False (examples: signs, buttons, stairs, etc)
     */
    public boolean renderAsNormalBlock()
    {
        return true;
    }
    
    /**
     * Return whether this block can drop from an explosion.
     */
    public boolean canDropFromExplosion(Explosion par1Explosion)
    {
        return false;
    }

    /**
     * only called by clickMiddleMouseButton , and passed to inventory.setCurrentItem (along with isCreative)
     */
    public int idPicked(World par1World, int par2, int par3, int par4)
    {
        return mod_DesertPetrifiedWood.BlockPetrifiedWood2.blockID;
    }


 /**
     * Drops the block items with a specified chance of dropping the specified items
     */
    public void dropBlockAsItemWithChance(World par1World, int par2, int par3, int par4, int par5, float par6, int par7)
    {
        super.dropBlockAsItemWithChance(par1World, par2, par3, par4, par5, par6, par7);

        if (this.idDropped(par5, par1World.rand, par7) != this.blockID)
        {
            int var8 = 0;

            if (this.blockID == mod_DesertPetrifiedWood.BlockPetrifiedWood.blockID)
            {
                var8 = MathHelper.getRandomIntegerInRange(par1World.rand, 0, 2);
            }
            
            this.dropXpOnBlockBreak(par1World, par2, par3, par4, var8);
        }
    }
}

