/** code generated by Kinyoshi */
package net.minecraft.src;

import java.io.*;
import java.util.*;

import net.minecraft.client.Minecraft;

public class mod_DesertPetrifiedWood extends BaseMod
{
	public mod_DesertPetrifiedWood()
	{

		readWriteProperties();

        BlockPetrifiedWood = (new BlockPetrifiedWood(BlockPetrifiedWoodID)).setHardness(12.0F).setResistance(10.0F).setLightValue(0.0F).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("BlockPetrifiedWood");
        ModLoader.addName(BlockPetrifiedWood, "Petrified Wood");
  //      BlockPetrifiedWood.setCreativeTab(CreativeTabs.tabBlock);
        BlockPetrifiedWood2 = (new BlockPetrifiedWood2(BlockPetrifiedWood2ID)).setHardness(12.0F).setResistance(10.0F).setLightValue(0.0F).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("BlockPetrifiedWood");
        ModLoader.addName(BlockPetrifiedWood2, "Petrified Wood");
        BlockPetrifiedWood2.setCreativeTab(CreativeTabs.tabBlock);
        
        ItemPetrifiedWood = new Item(ItemPetrifiedWoodID).setUnlocalizedName("ItemPetrifiedWood");
        ItemCarbonizedWood = new Item(ItemCarbonizedWoodID).setUnlocalizedName("ItemCarbonizedWood");
        ItemPetrifiedWoodAxe = new ItemPetrifiedWoodAxe(ItemPetrifiedWoodAxeID, EnumPetrifiedWoodToolMaterial.PETRIFIEDWOOD).setUnlocalizedName("ItemPetrifiedWoodAxe");
        ItemPetrifiedWoodSpear = new ItemPetrifiedWoodSpear(ItemPetrifiedWoodSpearID, EnumPetrifiedWoodToolMaterial.PETRIFIEDWOOD).setUnlocalizedName("ItemPetrifiedWoodSpear");
        
        ModLoader.addName(ItemPetrifiedWood, "Petrified Wood");
        ItemPetrifiedWood.setCreativeTab(CreativeTabs.tabMaterials);
        
        ModLoader.addName(ItemCarbonizedWood, "Carbonized Wood");
        ItemCarbonizedWood.setCreativeTab(CreativeTabs.tabMaterials);
 
        ModLoader.addName(ItemPetrifiedWoodAxe, "Petrified Wood Axe");
        ItemPetrifiedWoodAxe.setCreativeTab(CreativeTabs.tabTools);
        
        ModLoader.addName(ItemPetrifiedWoodSpear, "Petrified Wood Spear");
        ItemPetrifiedWoodSpear.setCreativeTab(CreativeTabs.tabTools);
        
        ModLoader.addSmelting(ItemPetrifiedWood.itemID, new ItemStack(ItemCarbonizedWood, 1), 0.1F);
        ModLoader.addRecipe(new ItemStack(ItemPetrifiedWoodSpear, 1), new Object[] {"  C", " S ",  "S  ", 'C', ItemPetrifiedWood, 'S', Item.stick});
        ModLoader.addRecipe(new ItemStack(ItemPetrifiedWoodAxe, 1), new Object[] {"CC ", "CS ", " S ", 'C', ItemPetrifiedWood, 'S', Item.stick});
        ModLoader.addRecipe(new ItemStack(Item.stick, 2), new Object[] {"C", 'C', ItemPetrifiedWood});

    }

	public void readWriteProperties() {
		Properties properties = new Properties();
		try
		{
            File file = new File((new StringBuilder()).append(Minecraft.getMinecraftDir()).append("/mods/DesertPetrifiedWood.config").toString());
            boolean flag = file.createNewFile();
            if(flag)
            {
                FileOutputStream fileoutputstream = new FileOutputStream(file);
                properties.setProperty("BlockPetrifiedWoodID", Integer.toString(253));
                properties.setProperty("BlockPetrifiedWood2ID", Integer.toString(254));
                properties.setProperty("ItemPetrifiedWoodID", Integer.toString(3328));
                properties.setProperty("ItemCarbonizedWoodID", Integer.toString(3329));
              	properties.setProperty("ItemPetrifiedWoodAxeID", Integer.toString(3330));
                properties.setProperty("ItemPetrifiedWoodSpearID", Integer.toString(3331));
                properties.setProperty("ShouldMoreOreSpawn", Boolean.toString(false));
                properties.store(fileoutputstream, "Change the ID's to fix ID incompatibilities.");
                fileoutputstream.close();
            }
            properties.load(new FileInputStream((new StringBuilder()).append(Minecraft.getMinecraftDir()).append("/mods/DesertPetrifiedWood.config").toString()));
            BlockPetrifiedWoodID = Integer.parseInt(properties.getProperty("BlockPetrifiedWoodID"));
            BlockPetrifiedWood2ID = Integer.parseInt(properties.getProperty("BlockPetrifiedWood2ID"));
            ItemPetrifiedWoodID = Integer.parseInt(properties.getProperty("ItemPetrifiedWoodID"));
            ItemCarbonizedWoodID = Integer.parseInt(properties.getProperty("ItemCarbonizedWoodID"));
            ItemPetrifiedWoodAxeID = Integer.parseInt(properties.getProperty("ItemPetrifiedWoodAxeID"));
            ItemPetrifiedWoodSpearID = Integer.parseInt(properties.getProperty("ItemPetrifiedWoodSpearID"));
            ShouldMoreOreSpawn = Boolean.parseBoolean(properties.getProperty("ShouldMoreOreSpawn"));
        }
        catch(IOException ioexception)
        {
            ioexception.printStackTrace();
            BlockPetrifiedWoodID = 253;
            BlockPetrifiedWood2ID = 254;
            ItemPetrifiedWoodID = 3328;
            ItemCarbonizedWoodID = 3329;
            ItemPetrifiedWoodAxeID = 3330;
            ItemPetrifiedWoodSpearID = 3331;
            ShouldMoreOreSpawn = false;
        }
	}
	
	public String getVersion() {
		return "MineCraft1.5.2__DesertPetrifiedWood1.5.2r1";
	}

	public int addFuel(int par1, int par2)
    {
        if(par1 == ItemCarbonizedWood.itemID)
        {
            return 3200;
        }
        return 0;
    }

    public void generateSurface(World world, Random r, int i, int j)
 {
 	if (ShouldMoreOreSpawn == true)
	{
    for(int k = 0; k < 5 + r.nextInt(18); k++)
    {
         int randPosX = i + r.nextInt(16);
         int randPosY = r.nextInt(256);
         int randPosZ = j + r.nextInt(16);
         //on sand
         (new WorldGenPetrifiedWood()).generate(world, r, randPosX, randPosY, randPosZ);
    }
    
    for(int k = 0; k < 7 + r.nextInt(21); k++)
    {
         int randPosX = i + r.nextInt(16);
         int randPosY = r.nextInt(256);
         int randPosZ = j + r.nextInt(16);
         //in stone
         (new WorldGenMinable(BlockPetrifiedWood2.blockID, 2 + r.nextInt(7))).generate(world, r, randPosX, randPosY, randPosZ);
    }
    
    for(int k = 0; k < 9 + r.nextInt(18); k++)
    {
         int randPosX = i + r.nextInt(16);
         int randPosY = r.nextInt(256);
         int randPosZ = j + r.nextInt(16);
         //in dirt
         (new WorldGenPetrifiedWood2(BlockPetrifiedWood2.blockID, 2 + r.nextInt(5))).generate(world, r, randPosX, randPosY, randPosZ);
    }
    
    for(int k = 0; k < 10 + r.nextInt(16); k++)
    {
         int randPosX = i + r.nextInt(16);
         int randPosY = r.nextInt(256);
         int randPosZ = j + r.nextInt(16);
         //in grass
         (new WorldGenPetrifiedWood3(BlockPetrifiedWood2.blockID, 2 + r.nextInt(6))).generate(world, r, randPosX, randPosY, randPosZ);
         
    }
    
    for(int k = 0; k < 2 + r.nextInt(3); k++)
    {
         int randPosX = i + r.nextInt(16);
         int randPosY = r.nextInt(256);
         int randPosZ = j + r.nextInt(16);
         //in wood
         (new WorldGenPetrifiedWood4(BlockPetrifiedWood2.blockID, 1 + r.nextInt(4))).generate(world, r, randPosX, randPosY, randPosZ);
         
    }
	}
	else
	{
    for(int k = 0; k < 3 + r.nextInt(12); k++)
    {
         int randPosX = i + r.nextInt(16);
         int randPosY = r.nextInt(256);
         int randPosZ = j + r.nextInt(16);
         //on sand
         (new WorldGenPetrifiedWood()).generate(world, r, randPosX, randPosY, randPosZ);
    }
    
    for(int k = 0; k < 4 + r.nextInt(16); k++)
    {
         int randPosX = i + r.nextInt(16);
         int randPosY = r.nextInt(256);
         int randPosZ = j + r.nextInt(16);
         //in stone
         (new WorldGenMinable(BlockPetrifiedWood2.blockID, 1 + r.nextInt(3))).generate(world, r, randPosX, randPosY, randPosZ);
    }
    
    for(int k = 0; k < 6 + r.nextInt(14); k++)
    {
         int randPosX = i + r.nextInt(16);
         int randPosY = r.nextInt(256);
         int randPosZ = j + r.nextInt(16);
         //in dirt
         (new WorldGenPetrifiedWood2(BlockPetrifiedWood2.blockID, 1 + r.nextInt(4))).generate(world, r, randPosX, randPosY, randPosZ);
    }
    
    for(int k = 0; k < 6 + r.nextInt(14); k++)
    {
         int randPosX = i + r.nextInt(16);
         int randPosY = r.nextInt(256);
         int randPosZ = j + r.nextInt(16);
         //in grass
         (new WorldGenPetrifiedWood3(BlockPetrifiedWood2.blockID, 1 + r.nextInt(4))).generate(world, r, randPosX, randPosY, randPosZ);
         
    }
    
    for(int k = 0; k < 2 + r.nextInt(3); k++)
    {
         int randPosX = i + r.nextInt(16);
         int randPosY = r.nextInt(256);
         int randPosZ = j + r.nextInt(16);
         //in wood
         (new WorldGenPetrifiedWood4(BlockPetrifiedWood2.blockID, r.nextInt(3))).generate(world, r, randPosX, randPosY, randPosZ);
         
    }
	}
 }
          
    public static Block BlockPetrifiedWood;
    public static int BlockPetrifiedWoodID;
    public static Block BlockPetrifiedWood2;
    public static int BlockPetrifiedWood2ID;
    
    public static Item ItemPetrifiedWood;
    public static int ItemPetrifiedWoodID;
    public static Item ItemCarbonizedWood;
    public static int ItemCarbonizedWoodID;
    public static Item ItemPetrifiedWoodAxe;
    public static int ItemPetrifiedWoodAxeID;
    public static Item ItemPetrifiedWoodSpear;
    public static int ItemPetrifiedWoodSpearID;
    public static boolean ShouldMoreOreSpawn;

	public void load()
	{
		ModLoader.registerBlock(BlockPetrifiedWood);
		ModLoader.registerBlock(BlockPetrifiedWood2);
	}
}
